import { chromium } from 'playwright';
import {mkdir,writeFile} from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--enable-webgl','--ignore-gpu-blocklist']});
const page=await browser.newPage({viewport:{width:1440,height:900}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
await mkdir('test-results',{recursive:true});
await page.goto('http://127.0.0.1:5173');
await page.waitForTimeout(2000);
await page.screenshot({path:'test-results/title.png'});
console.log('Title:',await page.title(),'errors:',errors);
await page.locator('#character-name').fill(`Browser${String(Date.now()).slice(-6)}`);
await page.locator('#character-role').selectOption('Valkyrie');
await page.locator('#enter-dungeon').click();
await page.waitForFunction(()=>window.descent?.state.playing,{},{timeout:15000});
await page.waitForTimeout(2000);
console.log('Game:',await page.evaluate(()=>window.descent.state));
assert.equal(await page.evaluate(()=>window.descent.state.player.race),'human');
await page.screenshot({path:'test-results/game.png'});
const start=await page.evaluate(()=>window.descent.state.player);
await page.locator('#mouse-capture').click();
await page.keyboard.down('w');await page.waitForTimeout(2000);await page.keyboard.up('w');
const moved=await page.evaluate(()=>window.descent.state.player);
assert.ok(moved.x!==start.x||moved.y!==start.y,'WASD changes actual engine position');
await page.keyboard.down('Control');await page.waitForTimeout(200);
assert.equal(await page.evaluate(()=>window.descent.state.pose.crouch),true);await page.keyboard.up('Control');
await page.keyboard.press('i');
const beforeInventory=await page.evaluate(()=>window.descent.state.player.turn);
await page.waitForTimeout(3000);
assert.ok(await page.evaluate(()=>window.descent.state.player.turn)>beforeInventory,'time advances in inventory');
console.log('Inventory:',await page.locator('#panel-title').textContent(),'state:',await page.evaluate(()=>window.descent.state));
await page.screenshot({path:'test-results/inventory.png'});
await page.locator('[data-item-key="b"]').click();await page.locator('[data-inventory-action="w"]').click();
await page.waitForFunction(()=>window.descent.state.player.weapon.includes('dagger'));
console.log('Inventory wield succeeded.');
await page.keyboard.press('Escape');
await page.keyboard.press('Tab');
await page.locator('#command-search').fill('save');
await page.locator('[data-palette-key="S"]').click();
await page.waitForTimeout(1500);
console.log('Save prompt:',await page.locator('#panel-title').textContent().catch(()=>null));
const yes=page.locator('[data-choice="y"]');if(await yes.count())await yes.click();
await page.waitForTimeout(1800);
console.log('After save:',await page.evaluate(()=>window.descent.state),'errors:',errors);
assert.equal(await page.locator('.title-screen').isVisible(),true,'save returns to title');
await page.locator('#continue-game').click();
await page.waitForFunction(()=>window.descent.state.playing);
assert.ok((await page.evaluate(()=>window.descent.state.player.weapon)).includes('dagger'),'continue preserves wielded dagger');
await page.keyboard.press('Tab');await page.locator('#command-search').fill('save');await page.locator('[data-palette-key="S"]').click();
await page.locator('[data-choice="y"]').waitFor({timeout:8000});await page.locator('[data-choice="y"]').click();await page.waitForTimeout(1000);
await writeFile('test-results/browser-errors.json',JSON.stringify(errors,null,2));
await browser.close();
if(errors.length)process.exitCode=1;
